import Footer from '@/components/footer';
import Navbar from '@/components/navbar';
import { poppins } from '@/components/ui/fonts';
import { ApolloProvider } from '@/provider/ApolloProvider';
import LocationProvider from '@/provider/LocationProvider';
import { MapProvider } from '@/provider/MapsProvider';
import { PrimeReactProvider } from '@/provider/PrimeReactProvider';
import type { Metadata } from 'next';
import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <ApolloProvider>
          <PrimeReactProvider>
            <LocationProvider>
              <MapProvider>
                <Navbar />
                {children}
                <Footer />
              </MapProvider>
            </LocationProvider>
          </PrimeReactProvider>
        </ApolloProvider>
      </body>
    </html>
  );
}
